# Custom Language File for Launcher Customizer

[ejs.app]
title = "공돌서버"

[ejs.landing]
mediaGitHubURL = "https://github.com/gongdol2da/gongdolserver"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/Y5uCb3B3UT"
mediaAfreecaTVURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/gongdol2da/gongdolserver"
supportLink = "https://github.com/gongdol2da/gongdolserver/issues"

[ejs.welcome]
welcomeHeader = "공돌서버"
welcomeDescription = "첫째 줄.<br>둘째 줄.<br>셋째줄."
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."